In [2]:
# Importando as bibliotecas gerais:
import numpy as np
import matplotlib.pyplot as plt

# Importando as bibliotecas Scikit Learn:
from sklearn.naive_bayes import BernoulliNB
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import confusion_matrix
from sklearn.pipeline import make_pipeline
from sklearn.feature_extraction.text import CountVectorizer

In [3]:
ME = np.array([[2, 0, 0, 0, 1, 2, 3, 1],
               [0, 0, 1, 0, 2, 1, 0, 0],
               [0, 1, 0, 1, 0, 2, 1, 0],
               [1, 0, 0, 2, 0, 1, 0, 1],
               [2, 0, 0, 0, 1, 0, 1, 3],
               [0, 0, 1, 2, 0, 0, 2, 1]])

MI = np.array([[0, 1, 1, 0, 0, 0, 1, 0],
               [1, 2, 0, 1, 0, 0, 1, 1],
               [0, 1, 1, 0, 0, 2, 0, 0],
               [0, 0, 0, 0, 0, 0, 0, 0],
               [0, 0, 1, 0, 1, 0, 1, 0]])


In [4]:
label_names = ['goal', 'tutor', 'variance', 'speed', 'drink', 'defence', 'performance', 'field']

In [16]:
x_train = np.array([[2, 0, 0, 0, 1, 2, 3, 1],
                    [0, 0, 1, 0, 2, 1, 0, 0],
                    [0, 1, 0, 1, 0, 2, 1, 0],
                    [1, 0, 0, 2, 0, 1, 0, 1],
                    [2, 0, 0, 0, 1, 0, 1, 3],
                    [0, 0, 1, 2, 0, 0, 2, 1],
                    [0, 1, 1, 0, 0, 0, 1, 0],
                    [1, 2, 0, 1, 0, 0, 1, 1],
                    [0, 1, 1, 0, 0, 2, 0, 0],
                    [0, 0, 0, 0, 0, 0, 0, 0],
                    [0, 0, 1, 0, 1, 0, 1, 0]])

In [17]:
y_train = np.array(['sport', 'informatic', 'informatic', 'sport','sport', 'informatic', 'sport', 'informatic', 'sport', 'informat', 'informatic'])

In [18]:
x_test_1 = np.array([[2, 1, 0, 0, 1, 2, 0, 1]])
x_test_2 = np.array([[0, 1, 1, 0, 1, 0, 1, 0]])

# **Multinomial**

In [19]:
# Instânciando o Multinomial NB
MNB = MultinomialNB()

# Fazendo o treinamento:
MNB.fit(x_train, y_train) 

MultinomialNB(alpha=1.0, class_prior=None, fit_prior=True)

In [26]:
# Fazendo a predição oara o teste 1:
y_pred = MNB.predict(x_test_1)

# Imprimindo o resultado:
print('A predição do algorítmo de Multinomial: {}'.format(y_pred[0]))

A predição do algorítmo de Multinomial: sport


In [23]:
# Fazendo a predição para o teste 2:
y_pred = MNB.predict(x_test_2)

# Imprimindo o resultado:
print('A predição do algorítmo de Multinomial: {}'.format(y_pred[0]))

A predição do algorítmo de Multinomial: informatic


In [34]:
# Imprimindo as probabilidades encontradas:
print('As probabilidades encontradas para o teste 1 foram:')
print(MNB.predict_proba(x_test_1))

As probabilidades encontradas para o teste 1 foram:
[[0.08848049 0.08295046 0.82856904]]


In [35]:
# Imprimindo as probabilidades encontradas:
print('As probabilidades encontradas para o teste 1 foram:')
print(MNB.predict_proba(x_test_2))

As probabilidades encontradas para o teste 1 foram:
[[0.09546258 0.71596936 0.18856806]]


# **Bernoulli**

In [29]:
# Instânciando o Multinomial NB
BNB = BernoulliNB()

# Fazendo o treinamento:
BNB.fit(x_train, y_train) 

BernoulliNB(alpha=1.0, binarize=0.0, class_prior=None, fit_prior=True)

In [30]:
# Fazendo a predição oara o teste 1:
y_pred = BNB.predict(x_test_1)

# Imprimindo o resultado:
print('A predição do algorítmo de Multinomial: {}'.format(y_pred[0]))

A predição do algorítmo de Multinomial: sport


In [32]:
# Fazendo a predição para o teste 2:
y_pred = BNB.predict(x_test_2)

# Imprimindo o resultado:
print('A predição do algorítmo de Multinomial: {}'.format(y_pred[0]))

A predição do algorítmo de Multinomial: informatic


In [36]:
# Imprimindo as probabilidades encontradas:
print('As probabilidades encontradas para o teste 1 foram:')
print(BNB.predict_proba(x_test_1))

As probabilidades encontradas para o teste 1 foram:
[[0.03615659 0.07499646 0.88884694]]


In [37]:
# Imprimindo as probabilidades encontradas:
print('As probabilidades encontradas para o teste 1 foram:')
print(BNB.predict_proba(x_test_2))

As probabilidades encontradas para o teste 1 foram:
[[0.04640356 0.7129693  0.24062714]]
